from django_seed import Seed
from .models import *
import random

def continents():
    continents = ["North America", "South America", "Europe", "Africa", "Asia", "Australia"]

    for i in range(0, 6):
        seeder = Seed.seeder()
        seeder.add_entity(Continent,1,{
            'name' : lambda x : continents[i],
        })
        pks = seeder.execute()
        print(pks)

def countries():
    countries = [
    ["Afghanistan",4],
    ["Albania",3],
    ["Algeria",4],
    ["Andorra",3],
    ["Angola",4],
    ["Anguilla",6],
    ["Argentina",2],
    ["Armenia",5],
    ["Aruba",6],
    ["Australia",6],
    ["Austria",3],
    ["Azerbaijan",5],
    ["Bahamas",2],
    ["Bahrain",4],
    ["Bangladesh",4],
    ["Barbados",6],
    ["Belarus",3],
    ["Belgium",3],
    ["Belize",2],
    ["Benin",4],
    ["Bermuda",2],
    ["Bhutan",5],
    ["Bolivia",2],
    ["Bosnia & Herzegovina",3],
    ["Botswana",4],
    ["Brazil",2],
    ["Bulgaria",3],
    ["Burkina Faso",4],
    ["Burundi",4],
    ["Cambodia",5],
    ["Cameroon",4],
    ["Canada",1],
    ["Cape Verde",4],
    ["Cayman Islands",1],
    ["Central African Republic",4],
    ["Chad",4],
    ["Chile",2],
    ["China",5],
    ["Christmas Island",6],
    ["Cocos",5],
    ["Colombia",2],
    ["Comoros",4],
    ["Congo",4],
    ["Cook Islands",6],
    ["Costa Rica",4],
    ["Croatia",3],
    ["Cuba",1],
    ["Curaçao",2],
    ["Cyprus",5],
    ["Czechia",3],
    ["Côte d’Ivoire",4],
    ["Denmark",3],
    ["Djibouti",4],
    ["Dominica",1],
    ["Dominican Republic",1],
    ["Ecuador",2],
    ["Egypt",4],
    ["El Salvador",1],
    ["Equatorial Guinea",4],
    ["Eritrea",4],
    ["Estonia",3],
    ["Eswatini",4],
    ["Ethiopia",4],
    ["Falkland Islands",2],
    ["Faroe Islands",3],
    ["Fiji",6],
    ["Finland",3],
    ["France",3],
    ["French Guiana",2],
    ["French Polynesia",6],
    ["French Southern Territories",4],
    ["Gabon",4],
    ["Gambia",4],
    ["Georgia",5],
    ["Germany",3],
    ["Ghana",4],
    ["Gibraltar",4],
    ["Greece",3],
    ["Greenland",3],
    ["Grenada",2],
    ["Guadeloupe",2],
    ["Guam",5],
    ["Guatemala",1],
    ["Guernsey",3],
    ["Guinea",4],
    ["Guinea-Bissau",4],
    ["Guyana",4],
    ["Haiti",1],
    ["Honduras",1],
    ["Hong Kong",5],
    ["Hungary",3],
    ["Iceland",3],
    ["India",5],
    ["Indonesia",5],
    ["Iran",5],
    ["Iraq",5],
    ["Ireland",3],
    ["Isle of Man",3],
    ["Israel",5],
    ["Italy",3],
    ["Jamaica",1],
    ["Japan",5],
    ["Jersey",3],
    ["Jordan",5],
    ["Kazakhstan",5],
    ["Kenya",4],
    ["Kiribati",6],
    ["Kosovo",3],
    ["Kuwait",5],
    ["Kyrgyzstan",5],
    ["Laos",5],
    ["Latvia",3],
    ["Lebanon",4],
    ["Lesotho",4],
    ["Liberia",4],
    ["Libya",4],
    ["Liechtenstein",3],
    ["Lithuania",3],
    ["Luxembourg",3],
    ["Madagascar",4],
    ["Malawi",4],
    ["Malaysia",5],
    ["Maldives",5],
    ["Mali",4],
    ["Malta",3],
    ["Marshall Islands",6],
    ["Martinique",2],
    ["Mauritania",4],
    ["Mauritius",5],
    ["Mayotte",4],
    ["Mexico",2],
    ["Micronesia",6],
    ["Moldova",3],
    ["Monaco",3],
    ["Mongolia",5],
    ["Montenegro",3],
    ["Montserrat",3],
    ["Morocco",4],
    ["Mozambique",4],
    ["Myanmar",5],
    ["Namibia",4],
    ["Nauru",4],
    ["Nepal",5],
    ["Netherlands",3],
    ["New Caledonia",6],
    ["New Zealand",6],
    ["Nicaragua",1],
    ["Niger",4],
    ["Nigeria",4],
    ["Niue",6],
    ["Norfolk Island",6],
    ["North Korea",5],
    ["North Macedonia",3],
    ["Northern Cyprus",3],
    ["Northern Mariana Islands",1],
    ["Norway",3],
    ["Oman",5],
    ["Pakistan",5],
    ["Palau",5],
    ["Palestinian Territories",5],
    ["Panama",1],
    ["Papua New Guinea",6],
    ["Paraguay",2],
    ["Peru",2],
    ["Philippines",5],
    ["Pitcairn Islands",6],
    ["Poland",3],
    ["Portugal",3],
    ["Puerto Rico",2],
    ["Qatar",5],
    ["Romania",3],
    ["Russia",3],
    ["Rwanda",4],
    ["Réunion",4],
    ["Sahrawi Arab Democratic Republic",4],
    ["Samoa",6],
    ["San Marino",3],
    ["Saudi Arabia",5],
    ["Senegal",4],
    ["Serbia",3],
    ["Seychelles",4],
    ["Sierra Leone",4],
    ["Singapore",5],
    ["Sint Maarten",1],
    ["Slovakia",3],
    ["Slovenia",3],
    ["Solomon Islands",6],
    ["Somalia",4],
    ["Somaliland",4],
    ["South Africa",4],
    ["South Korea",5],
    ["South Ossetia",5],
    ["South Sudan",4],
    ["Spain",3],
    ["Sri Lanka",5],
    ["St. Barthélemy",1],
    ["St. Helena",4],
    ["St. Kitts & Nevis",1],
    ["St. Lucia",1],
    ["St. Martin",1],
    ["St. Pierre & Miquelon",1],
    ["St. Vincent & Grenadines",1],
    ["Sudan",4],
    ["Suriname",2],
    ["Svalbard & Jan Mayen",3],
    ["Sweden",3],
    ["Switzerland",3],
    ["Syria",5],
    ["São Tomé & Príncipe",4],
    ["Taiwan",5],
    ["Tajikistan",5],
    ["Tanzania",4],
    ["Thailand",5],
    ["Timor-Leste",5],
    ["Togo",4],
    ["Tokelau",6],
    ["Tonga",6],
    ["Transnistria",3],
    ["Trinidad & Tobago",2],
    ["Tunisia",4],
    ["Turkey",5],
    ["Turkmenistan",5],
    ["Turks & Caicos Islands",1],
    ["Tuvalu",6],
    ["U.S. Outlying Islands",2],
    ["U.S. Virgin Islands",1],
    ["Uganda",4],
    ["Ukraine",3],
    ["United Arab Emirates",5],
    ["United Kingdom",3],
    ["United States",1],
    ["Uruguay",2],
    ["Uzbekistan",5],
    ["Vanuatu",6],
    ["Vatican City",3],
    ["Venezuela",2],
    ["Vietnam",5],
    ["Wallis & Futuna",6],
    ["Western Sahara",4],
    ["Yemen",5],
    ["Zambia",4],
    ["Zimbabwe",4]
    ]

    for c in countries:
        id = Continent.objects.get(id=c[1])
        seeder = Seed.seeder()
        seeder.add_entity(Country,1,{
            'name' : lambda x : c[0],
            'continent' : lambda x : id
        })
        pks = seeder.execute()
        print(pks)

